src_vocab_path: /mnt/d/file/nlp/exp3/nmt_experiment/nmt_experiment/data/spm_corpus/vocab.zh.json
tgt_vocab_path: /mnt/d/file/nlp/exp3/nmt_experiment/nmt_experiment/data/spm_corpus/vocab.en.json
src_train_corpus_path: /mnt/d/file/nlp/exp3/nmt_experiment/nmt_experiment/data/spm_corpus/train.bpe.filter.zh-en.zh
tgt_train_corpus_path: /mnt/d/file/nlp/exp3/nmt_experiment/nmt_experiment/data/spm_corpus/train.bpe.filter.zh-en.en
src_valid_corpus_path: /mnt/d/file/nlp/exp3/nmt_experiment/nmt_experiment/data/spm_corpus/valid.bpe.filter.zh-en.zh
tgt_valid_corpus_path: /mnt/d/file/nlp/exp3/nmt_experiment/nmt_experiment/data/spm_corpus/valid.bpe.filter.zh-en.en
save_dir: /mnt/d/file/nlp/exp3/nmt_experiment/nmt_experiment/data/checkpoint
num_encoder_layers: 3
num_decoder_layers: 3
d_model: 256
d_ff: 1024
num_heads: 4
epoch: 30
batch_size: 32
dropout: 0.1
learning_rate: 0.0007
adam_beta1: 0.9
adam_beta2: 0.98
label_smoothing: 0.1
log_interval: 100
cuda: true
seed:  1
